name: Feature Request
description: Suggest a feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for your feature suggestion!
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to be implemented?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
    validations:
      required: false